Repository emotional-cities/pluma-experiments, pull requests merged in 2024-04, with the labels that each got.

#24 Add streaming status control panel visualizer
  Workflows/ExperimentAcquisition.bonsai
  Workflows/Extensions.csproj
  Workflows/Extensions/ParseNavHPPOSLLH.cs
  Workflows/Extensions/StreamingStatus.cs
  Workflows/Extensions/StreamingStatusVisualizer.cs
Labels: feature

#59 Add VR latency benchmarks
  Benchmarks/VRLatencyExperiment/Analysis/Data230227/round-trip-timestamps-diffs.csv
  Benchmarks/VRLatencyExperiment/Analysis/Data230227/round-trip-timestamps.csv
  Benchmarks/VRLatencyExperiment/Analysis/Data230227/switch-times-3.csv
  Benchmarks/VRLatencyExperiment/Analysis/Data230227/switch-times-unity-3.csv
  Benchmarks/VRLatencyExperiment/Analysis/Data230227/switch-times-unity.csv
  Benchmarks/VRLatencyExperiment/Analysis/Data230227/switch-times.csv
  Benchmarks/VRLatencyExperiment/Analysis/analysis.ipynb
  Benchmarks/VRLatencyExperiment/Analysis/correlation-analysis.ipynb
  Benchmarks/VRLatencyExperiment/Analysis/zmq-events.csv
  Benchmarks/VRLatencyExperiment/Bonsai/Bonsai.config
  Benchmarks/VRLatencyExperiment/Bonsai/NuGet.config
  Benchmarks/VRLatencyExperiment/Bonsai/Setup.cmd
  Benchmarks/VRLatencyExperiment/Bonsai/Setup.ps1
  Benchmarks/VRLatencyExperiment/Workflows/vr-photodiode-random-sequence.bonsai
  Benchmarks/VRLatencyExperiment/Workflows/vr-photodiode-random-sequence.bonsai.layout
  Benchmarks/VRLatencyExperiment/Workflows/vr-photodiode-random-sequence_WithHarpWritebonsai
  Benchmarks/VRLatencyExperiment/Workflows/vr-photodiode-random-sequence_WithLatestFrom.bonsai
  Benchmarks/VRLatencyExperiment/Workflows/vr-photodiode.bonsai
  Benchmarks/VRLatencyExperiment/Workflows/vr-random-sequence.bonsai
Labels: benchmark

#63 Replace local dependencies with published packages
  Bonsai/Bonsai.config
  Bonsai/Setup.cmd
  Bonsai/Setup.ps1
  LocalPackages/Bonsai.Zyre.0.1.0-rc3.nupkg
  LocalPackages/Harp.Pluma.0.1.0-preview1.nupkg
  LocalPackages/PupilInterface.0.1.0-rc2.nupkg
  Workflows/ExperimentAcquisition.bonsai
  Workflows/ExperimentAcquisitionVR.bonsai
  Workflows/Extensions/EmpaticaClient.cs
  Workflows/Extensions/FFmpeg.AutoGen.Abstractions.dll
  Workflows/Extensions/FFmpeg.AutoGen.Bindings.DynamicallyLoaded.dll
  Workflows/Extensions/WindSerial.cs
  Workflows/Extensions/lsl.dll
  Workflows/PostHoc_UBX_demux.bonsai
  Workflows/RoundTripPupil.bonsai
  Workflows/TestSynchronizer.bonsai
Labels: feature

#69 Scenario update 16
  VR-Alfama/Assets/Scenes/VR-Alfama.unity
  VR-Alfama/ProjectSettings/EditorBuildSettings.asset
Labels: VR
