Repository emotional-cities/pluma-experiments, pull requests merged in 2024-10, with the labels that each got.

#91 VR experimental protocol implementation and logging
  VR-Alfama/Assets/Scenes/VR-Alfama.unity
  VR-Alfama/Assets/Scripts/AddMeshColliderToChildren.cs
  VR-Alfama/Assets/Scripts/AddMeshColliderToChildren.cs.meta
  VR-Alfama/Assets/Scripts/EyeHitPosition.cs
  VR-Alfama/Assets/Scripts/EyeHitPosition.cs.meta
  VR-Alfama/Assets/Scripts/ImagePanel.cs
  VR-Alfama/Assets/Scripts/ImagePanel.cs.meta
  VR-Alfama/Assets/Scripts/MessagePanel.cs
  VR-Alfama/Assets/Scripts/MessagePanel.cs.meta
  VR-Alfama/Assets/Scripts/RayPointer.cs
  VR-Alfama/Assets/Scripts/RayPointer.cs.meta
  VR-Alfama/Assets/Scripts/RaycastDebug.cs
  VR-Alfama/Assets/Scripts/RaycastDebug.cs.meta
  VR-Alfama/Assets/Scripts/TrialSession.cs
  VR-Alfama/Assets/Scripts/TrialSession.cs.meta
  VR-Alfama/Assets/Scripts/UiManager.cs
  VR-Alfama/Assets/Scripts/UiManager.cs.meta
  VR-Alfama/Assets/Scripts/UiPanel.cs
  VR-Alfama/Assets/Scripts/UiPanel.cs.meta
  VR-Alfama/Assets/Scripts/VrUtilities.cs
  VR-Alfama/Assets/Scripts/VrUtilities.cs.meta
  VR-Alfama/Assets/Scripts/WorldPositionTest.cs
  VR-Alfama/Assets/Scripts/WorldPositionTest.cs.meta
  VR-Alfama/Assets/XrRig.prefab
  VR-Alfama/ProjectSettings/EditorBuildSettings.asset
  VR-Alfama/ProjectSettings/TagManager.asset
  Workflows/ExperimentAcquisitionVR.bonsai
  Workflows/ExperimentAcquisitionVR.bonsai.layout
  Workflows/Extensions.csproj
  Workflows/Extensions/ByteArrayToInt.cs
  Workflows/Extensions/Empatica.bonsai
  Workflows/Extensions/ParseAccelerometerString.cs
  Workflows/Extensions/ZeroMQLogging.bonsai
Labels: feature, fix, VR

#94 Normalize casing of word georeference
  VR-Alfama/Assets/Scenes/RoundTripTest.unity
  VR-Alfama/Assets/Scenes/VR-Alfama.unity
  VR-Alfama/Assets/Scripts/TrialSession.cs
  Workflows/ExperimentAcquisitionVR.bonsai
Labels: fix

#93 Add hotspot info in README.md
  README.md
Labels: documentation

#98 Remove unused nodes
  Workflows/Extensions/Empatica.bonsai
Labels: fix

#81 Update README.md Air Quality Bricklet
  README.md
Labels: documentation
